### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by fedelebrero** [saltstack-formulas/remi-formula#12]
Since remi-repo is dnf module based, this formula is not entirely valid for centos8 / rhel8.

See https://blog.remirepo.net/post/2019/12/03/Install-PHP-7.4-on-CentOS-RHEL-or-Fedora

**Comment by myii** [comment]
Thanks for the report @fedelebrero.

@kartnico, since you updated this formula recently, do you have any feedback regarding this?

**Comment by kartnico** [comment]
Hello,

It works for me. Maybe @fedelebrero ask a feature to manage "modules" but it is not a "bug". That's right ?

Regards,

**Comment by fedelebrero** [comment]
Effectively, that's right. My fault :-)

I will re-open this as a feature request. Thank you.

Regards,
